server {
    listen 80;
    server_name chat-ai.life www.chat-ai.life;
    # 将所有HTTP请求重定向到HTTPS
    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name chat-ai.life www.chat-ai.life;
    # SSL证书配置
    ssl_certificate /etc/nginx/certs/chat-ai.life.pem;
    ssl_certificate_key /etc/nginx/certs/chat-ai.life.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout 5m;

    # 开启gzip压缩
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
        # 缓存控制
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }
    # 后台api
    location /apis/{
        proxy_pass http://chat-ai-springboot:8089/;  # 关键修改
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # 处理大文件上传
        client_max_body_size    20M;
        proxy_request_buffering off;
    }
    # SSE流式传输
    location /apis/completions/ {
        proxy_pass http://chat-ai-springboot:8089/completions/;
        # 关键配置项
        proxy_buffering      off;    # 禁用缓冲
        proxy_read_timeout   5m;    # 保持长连接
        proxy_http_version   1.1;    # 使用HTTP 1.1
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # 禁用该路径的gzip
        gzip off;
    }
    # 静态资源长期缓存
    location /assets {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}